kind: PersistentVolume
apiVersion: v1
metadata:
  name: grafana-pv-volume
  labels:
    type: local
spec:
  storageClassName: longhorn
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce

