apiVersion: v1  
kind: PersistentVolumeClaim  
metadata:  
  name: grafana-data  
spec:
  storageClassName: longhorn
  accessModes:  
  - ReadWriteMany  
  resources:  
    requests:  
      storage: 1Gi