apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - env:
        - name: GF_INSTALL_PLUGINS
          value: grafana-piechart-panel, blackmirror1-singlestat-math-panel
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: admin
        image: grafana/grafana
        name: grafana
        volumeMounts:
        - mountPath: /etc/grafana/grafana.ini
          name: grafana-ini
          subPath: grafana.ini
          readOnly: true
        - mountPath: /etc/grafana/provisioning/dashboards/dashboards.yaml
          name: grafana-provisioning-dashboards
          subPath: dashboards.yaml
        - mountPath: /etc/grafana/provisioning/datasources/influxdb.yaml
          name: grafana-provisioning-datasources
          subPath: influxdb.yaml
        - mountPath: /var/lib/grafana/dashboards
          name: grafana-dashboards
          subPath: analysis-server.json
      restartPolicy: Always
      volumes:
        - name: grafana-ini
          configMap:
            name: grafana-ini

        - name: grafana-provisioning-dashboards
          configMap:
            name: grafana-provisioning-dashboards

        - name: grafana-provisioning-datasources
          configMap:
            name: grafana-provisioning-datasources

        - name: grafana-dashboards
          configMap:
            name: grafana-dashboards
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  selector:
    app: grafana
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
